# runs the tests and publishes if they pass.
# for now this is actually hourly
# or on demand
# see https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow
# see https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: Nightly

on:
  workflow_dispatch:
  schedule:
    # hourly
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install tools
        run: python -m pip install --upgrade pip setuptools wheel pytest pytest-cov

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Test with pytest
        run: pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      - name: Upload pytest test results 
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: junit/test-results.xml
        if: ${{ always() }}

      - name: write the version file
        # produces, for example, 2024.11.19.18.54
        run: python3 date.py > version.txt

      - name: check the version file
        run: cat version.txt

      - name: install pypa/build
        run: python3 -m pip install build --user

      - name: build a wheel and tarball
        # pyproject.toml references version.txt 
        run: python3 -m build

      - name: upload the dist
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-testpypi:
    needs:
      - build
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: download dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: publish to test.pypi.org
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
