# Checks out main, runs the tests, and publishes if they pass.
# Uses the output of date.py as the version.
#
# See https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow
# See https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: Nightly

on:
  workflow_dispatch:
  schedule:
    # Tries to run at midnight UTC.
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Specifies branch to build.
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Tools
        run: python -m pip install --upgrade pip build wheel pytest

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Test
        run: pytest tests

      - name: Write the version file
        run: python3 date.py > version.txt

      - name: Build
        run: python3 -m build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
