# runs the tests.

name: Python package

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Install tools
        run: python -m pip install --upgrade pip pytest pytest-cov

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Test
        run: pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      # - name: Upload test results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: pytest-results
      #     path: junit/test-results.xml
      #   if: ${{ always() }}

      - name: Publish test results
        # To make this work, you have to enable "read/write" permissions
        # in the "repo settings"
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: ${{ always() }}
        with:
           # Comments don't work with fork PRs anyway
           comment_mode: off
           files: |
             **/test*.xml
